//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INTEX.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class AssayTestCatalog
    {
        public int TestID { get; set; }
        public int AssayID { get; set; }
        public Nullable<int> TestConditionID { get; set; }

        public virtual Assay Assay { get; set; }
        public virtual Test Test { get; set; }
        public virtual TestCondition TestCondition { get; set; }
    }
}
