//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INTEX.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer()
        {
            this.Orders = new HashSet<Order>();
        }

        public int CustID { get; set; }

        [DisplayName("Name")]
        [Required]
        [StringLength(30, MinimumLength = 3, ErrorMessage = "Field must be from 3 to 30 characters.")]
        public string CustName { get; set; }

        [DisplayName("Phone Number")]
        [DataType(DataType.PhoneNumber, ErrorMessage = "Please enter a valid phone number.")]
        [Required]
        [StringLength(30, MinimumLength = 3, ErrorMessage = "Field must be from 3 to 30 characters.")]
        public string CustPhone { get; set; }

        [DisplayName("Email")]
        [DataType(DataType.EmailAddress, ErrorMessage = "Please enter a valid email address.")]
        [Required]
        [StringLength(30, MinimumLength = 3, ErrorMessage = "Field must be from 3 to 30 characters.")]
        public string CustEmail { get; set; }

        [DisplayName("Street Address 1")]
        [Required]
        [StringLength(30, MinimumLength = 3, ErrorMessage = "Field must be from 3 to 30 characters.")]
        public string CustStreetAddress1 { get; set; }

        [DisplayName("Street Address 2")]
        [StringLength(30, MinimumLength = 3, ErrorMessage = "Field must be from 3 to 30 characters.")]
        public string CustStreetAddress2 { get; set; }

        public Nullable<int> LocID { get; set; }

        public Nullable<int> AuthID { get; set; }

        public string UserID { get; set; }

        public virtual Authorization Authorization { get; set; }
        public virtual Location Location { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
    }
}
