//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INTEX.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer()
        {
            this.Orders = new HashSet<Order>();
        }
    
        public int CustID { get; set; }
        public string CustName { get; set; }
        public Nullable<System.DateTime> CustDOB { get; set; }
        public string CustPhone { get; set; }
        public string CustEmail { get; set; }
        public string CustStreetAddress1 { get; set; }
        public string CustStreetAddress2 { get; set; }
        public Nullable<int> LocID { get; set; }
        public Nullable<int> AuthID { get; set; }
        public string UserID { get; set; }
    
        public virtual Authorization Authorization { get; set; }
        public virtual Location Location { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
    }
}
