//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INTEX.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Invoice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Invoice()
        {
            this.Payments = new HashSet<Payment>();
        }

        public int InvoiceID { get; set; }

        public Nullable<int> OrderID { get; set; }

        [DisplayName("Payment Due Date")]
        [Required]
        [DataType(DataType.Date, ErrorMessage = "Please enter a valid date.")]
        public Nullable<System.DateTime> PaymentDueDate { get; set; }

        [DisplayName("Early Payment Date")]
        [Required]
        [DataType(DataType.Date, ErrorMessage = "Please enter a valid date.")]
        public Nullable<System.DateTime> EarlyPaymentDate { get; set; }

        [DisplayName("Early Payment Discount (Dollars)")]
        [Required]
        [DataType(DataType.Currency, ErrorMessage = "Please enter the early payment discount US dollars.")]
        public Nullable<decimal> EarlyPaymentDiscount { get; set; }

        [DisplayName("Date Sent")]
        [Required]
        [DataType(DataType.Date, ErrorMessage = "Please enter a valid date.")]
        public Nullable<System.DateTime> SentDate { get; set; }

        [DisplayName("Advanced Payment Amount")]
        [Required]
        [DataType(DataType.Currency, ErrorMessage = "Please enter advanced payment amount in US dollars.")]
        public Nullable<decimal> AdvancedAmount { get; set; }

        [DisplayName("Running Balance")]
        [Required]
        [DataType(DataType.Currency, ErrorMessage = "Please enter running balance in US dollars.")]
        public Nullable<decimal> RunningBalance { get; set; }

        public virtual Order Order { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payment> Payments { get; set; }
    }
}
