//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INTEX.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Location
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Location()
        {
            this.Customers = new HashSet<Customer>();
            this.Employees = new HashSet<Employee>();
        }

        public int LocID { get; set; }

        [DisplayName("City")]
        [Required]
        [RegularExpression(@"^[A-Z][a-zA-Z]", ErrorMessage = "Cities can only have alphabetic characters.")]
        [StringLength(30, ErrorMessage = "Field must be no longer than 30 characters.")]
        public string City { get; set; }

        public Nullable<int> RegionID { get; set; }

        [DisplayName("Postal Code")]
        [Required]
        [RegularExpression(@"^[0-9\-]", ErrorMessage = "Postal codes can only have numbers and dashes")]
        [StringLength(30, ErrorMessage = "Field must be no longer than 30 characters.")]
        public string Zip { get; set; }

        public Nullable<int> CountryID { get; set; }

        public virtual Country Country { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Customer> Customers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employee> Employees { get; set; }
        public virtual Region Region { get; set; }
    }
}
