//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INTEX.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Material
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Material()
        {
            this.SampleTestMaterials = new HashSet<SampleTestMaterial>();
            this.TestMaterials = new HashSet<TestMaterial>();
        }

        public int MaterialID { get; set; }

        [DisplayName("Material Name")]
        [Required]
        [StringLength(30, ErrorMessage = "Field must be no longer than 30 characters.")]
        public string MaterialName { get; set; }

        [DisplayName("Material Cost per Kilogram")]
        [Required]
        [DataType(DataType.Currency, ErrorMessage = "Enter cost of material per kilogram in US Dollars.")]
        public Nullable<decimal> MaterialCostPerKg { get; set; }

        [DisplayName("Materials on Hand (kilograms)")]
        [Required]
        public Nullable<decimal> MaterialOnHand { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SampleTestMaterial> SampleTestMaterials { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TestMaterial> TestMaterials { get; set; }
    }
}