//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INTEX.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SampleTest
    {
        public int SampleTestID { get; set; }
        public Nullable<int> OrderAssayID { get; set; }
        public Nullable<int> TestID { get; set; }
        public Nullable<int> CompoundSampleID { get; set; }
        public Nullable<decimal> ConductingCost { get; set; }
        public Nullable<decimal> BasePrice { get; set; }
        public Nullable<int> SampleTestWeight { get; set; }
        public Nullable<decimal> SampleTestConcentration { get; set; }
        public Nullable<int> TestCompleted { get; set; }
    
        public virtual CompoundSample CompoundSample { get; set; }
        public virtual OrderAssay OrderAssay { get; set; }
        public virtual Test Test { get; set; }
    }
}
