//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INTEX.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class SampleTest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SampleTest()
        {
            this.EmployeeTests = new HashSet<EmployeeTest>();
            this.SampleTestEquipments = new HashSet<SampleTestEquipment>();
            this.SampleTestMaterials = new HashSet<SampleTestMaterial>();
            this.Animals = new HashSet<Animal>();
        }

        public int SampleTestID { get; set; }

        public Nullable<int> OrderAssayID { get; set; }

        public Nullable<int> TestID { get; set; }

        public Nullable<int> CompoundSampleID { get; set; }

        [DisplayName("Test Conducting Cost")]
        [Required]
        [DataType(DataType.Currency, ErrorMessage = "Please enter test conducting cost in US Dollars.")]
        public Nullable<decimal> ConductingCost { get; set; }

        [DisplayName("Base Price")]
        [Required]
        [DataType(DataType.Currency, ErrorMessage = "Please enter base price cost in US Dollars.")]
        public Nullable<decimal> BasePrice { get; set; }

        [DisplayName("Test Sample Weight (mg)")]
        [Required]
        public Nullable<int> SampleTestWeight { get; set; }

        [DisplayName("Test Sample Concentration (mg/mL)")]
        [Required]
        public Nullable<decimal> SampleTestConcentration { get; set; }

        [DisplayName("Test Completed")]
        [Required]
        public Nullable<int> TestCompleted { get; set; }

        public virtual CompoundSample CompoundSample { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeTest> EmployeeTests { get; set; }
        public virtual OrderAssay OrderAssay { get; set; }
        public virtual Test Test { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SampleTestEquipment> SampleTestEquipments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SampleTestMaterial> SampleTestMaterials { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Animal> Animals { get; set; }
    }
}
